micronaut:
  application:
    name: mmorpg
  server:
    port: 8081
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
  executors:
    consumer:
      type: fixed
      nThreads: 15
    io:
      type: fixed
      nThreads: 75

mongodb:
  uri: mongodb://mongo_mmorpg:mongo_password@localhost:27017/mmorpg?authSource=admin
  options:
    maxConnectionIdleTime: 10000
    readConcern: majority
  cluster:
    maxWaitQueueSize: 5
  connectionPool:
    maxSize: 20

mongo-database:
  databaseName: "mmorpg"
  collectionName: "character"